name: C++ CI

on:
  push:
    branches:
      - main
      - stable/[0-9]+\.[0-9]+

jobs:
  start-vm:
    name: Start VM
    runs-on: trampoline
    outputs:
      label: ${{ steps.start-yc-runner.outputs.label }}
      instance-id: ${{ steps.start-yc-runner.outputs.instance-id }}
    steps:
      - name: Start YC runner
        id: start-yc-runner
        uses: yc-actions/yc-github-runner@v1
        with:
          mode: start
          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
          github-token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          folder-id: ${{ vars.YC_FOLDER_ID }}
          image-id: ${{ vars.YC_DEFAULT_IMAGE_ID }}
          zone-id: ${{ vars.YC_ZONE_ID }}
          subnet-id: ${{ vars.YC_SUBNET_ID }}
          cores: 16
          memory: 32GB
          core-fraction: 100
          disk-type: network-ssd-nonreplicated
          disk-size: 279GB

  checkout:
    name: Checkout sources
    needs: start-vm
    runs-on: ${{ needs.start-vm.outputs.label }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Checkout ydb
        uses: actions/checkout@v3
        repository: 
        ref: 

  check:
    name: Run checks
    needs:
      - start-vm
      - checkout
    runs-on: ${{ needs.start-vm.outputs.label }}
    steps:
      - name: Prepare python virtual environment
        shell: bash
        run: |
          python3.11 -m venv ../venv

      - name: Build Go
        shell: bash
        run: |
          cd yt/chyt/controller/cmd/chyt-controller
          export HOME=${RUNNER_WORKSPACE}
          /opt/go/bin/go build

      - name: Configure
        shell: bash
        run: |
          mkdir -p ../build
          cd ../build
          rm -rf *
          cmake \
            -G Ninja \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_TOOLCHAIN_FILE=../ytsaurus/clang.toolchain \
            -DCMAKE_C_COMPILER_LAUNCHER=ccache \
            -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
            ../ytsaurus

          mkdir -p ../build_debug
          cd ../build_debug
          rm -rf *
          cmake \
            -G Ninja \
            -DCMAKE_BUILD_TYPE=RelWithDebInfo \
            -DCMAKE_TOOLCHAIN_FILE=../ytsaurus/clang.toolchain \
            -DCMAKE_C_COMPILER_LAUNCHER=ccache \
            -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
            ../ytsaurus

      - name: Build
        shell: bash
        run: |
          cd ../build
          export CCACHE_BASEDIR="$(realpath ..)"
          export CCACHE_REMOTE_ONLY=true
          export CCACHE_REMOTE_STORAGE="${{ vars.CCACHE_REMOTE_STORAGE }}"
          ninja

          cd ../build_debug
          ninja ytserver-all

      - name: Build Python packages
        shell: bash
        run: |
          source ../venv/bin/activate
          YTSAURUS_COMMIT_HASH=${GITHUB_SHA} bash ./yt/python/packages/build_ytsaurus_packages.sh --ytsaurus-source-path $(pwd) --ytsaurus-build-path ../build

      - name: DockerHub login
        shell: bash
        run: |
          echo '${{ secrets.DOCKER_HUB_PASSWORD }}' | docker login --username ${{ secrets.DOCKER_HUB_LOGIN }} --password-stdin

      - name: Download SPYT
        uses: robinraju/release-downloader@v1.8
        with:
          latest: true
          fileName: "spyt-1.69.tar"

      - name: Download YQL
        uses: robinraju/release-downloader@v1.8
        with:
          latest: true
          fileName: "yql-package.tar"

      - name: Download benchmarks
        uses: robinraju/release-downloader@v1.8
        with:
          latest: true
          fileName: "benchmark-0.0.1.tgz"

      - name: Build and push ytsaurus docker image
        shell: bash
        run: |
          mkdir -p ../docker-ytsaurus-build

          tar -xf spyt-1.69.tar -C ../build
          tar -xf yql-package.tar -C ../build

          if [[ $GITHUB_REF =~ main$ ]];
          then
            IMAGE_TAG=dev
          elif [[ $GITHUB_REF =~ releases ]];
          then
            IMAGE_TAG=dev-${GITHUB_REF#refs/*/stable/}
          else
            IMAGE_TAG=nopush
          fi
          IMAGE_TAG_DEBUG=${IMAGE_TAG}-debug

          bash ./yt/docker/ytsaurus/build.sh --ytsaurus-source-path $(pwd) --ytsaurus-build-path ../build --ytsaurus-spyt-release-path ../build/spyt_release --ytsaurus-yql-package-path ../build/yql_package --output-path ../docker-ytsaurus-build --image-tag ${IMAGE_TAG}

          mv ../build_debug/yt/yt/server/all/ytserver-all ../build/yt/yt/server/all/ytserver-all
          bash ./yt/docker/ytsaurus/build.sh --ytsaurus-source-path $(pwd) --ytsaurus-build-path ../build --ytsaurus-spyt-release-path ../build/spyt_release --ytsaurus-yql-package-path ../build/yql_package --output-path ../docker-ytsaurus-build --image-tag ${IMAGE_TAG_DEBUG}

          if [[ $IMAGE_TAG != "nopush" ]];
          then
              docker push ytsaurus/ytsaurus:${IMAGE_TAG}
              docker tag ytsaurus/ytsaurus:${IMAGE_TAG} ytsaurus/ytsaurus-nightly:${IMAGE_TAG}-${GITHUB_SHA}
              docker push ytsaurus/ytsaurus-nightly:${IMAGE_TAG}-${GITHUB_SHA}

              docker push ytsaurus/ytsaurus:${IMAGE_TAG_DEBUG}
              docker tag ytsaurus/ytsaurus:${IMAGE_TAG_DEBUG} ytsaurus/ytsaurus-nightly:${IMAGE_TAG_DEBUG}-${GITHUB_SHA}
              docker push ytsaurus/ytsaurus-nightly:${IMAGE_TAG_DEBUG}-${GITHUB_SHA}
          fi

          if [[ $IMAGE_TAG == 'dev' ]];
          then
            docker tag ytsaurus/ytsaurus-nightly:${IMAGE_TAG}-${GITHUB_SHA} ytsaurus/ytsaurus-nightly:latest
            docker push ytsaurus/ytsaurus-nightly:latest
          fi

          cd yt/docker/local
          bash ./build.sh --ytserver-all ../../../../build/yt/yt/server/all/ytserver-all --image-tag ${IMAGE_TAG}
          bash ./build.sh --ytserver-all ../../../../build/yt/yt/server/all/ytserver-all --image-tag ${IMAGE_TAG_DEBUG}
          if [[ $IMAGE_TAG != "nopush" ]];
          then
              docker push ytsaurus/local:${IMAGE_TAG}
              docker push ytsaurus/local:${IMAGE_TAG_DEBUG}
          fi

      - name: Docker systest
        shell: bash
        run: |
          mkdir -p ../docker-systest-build
          bash ./yt/docker/systest/build.sh --ytsaurus-source-path $(pwd)  --ytsaurus-build-path ../build --benchmarks-path benchmark-0.0.1.tgz --output-path ../docker-systest-build --image-tag latest
          docker push ytsaurus/ytsaurus-systest:latest

      - name: Kube
        shell: bash
        run: |
          export HOME=/root
          bash yt/systest/scripts/minikube.sh --image ytsaurus/ytsaurus-nightly:latest --ytsaurus-source-path $(pwd)

      - name: Unittests
        shell: bash
        run: |
          cp ./yt/yt/scripts/run_unittests.sh ../build/
          cd ../build
          ./run_unittests.sh

      - name: Prepare pytest environment
        shell: bash
        run: |
          yt/yt/scripts/prepare_pytest_environment.sh

      - name: Integration tests
        shell: bash
        run: |
          yt/yt/scripts/run_integration_tests.sh

      - name: Python tests
        shell: bash
        run: |
          yt/yt/scripts/run_python_tests.sh

      - name: Testmo unittests upload
        shell: bash
        run: |
          export TESTMO_TOKEN="${{ secrets.NEBIUS_TESTMO_TOKEN }}"
          testmo automation:run:submit --instance https://nebius.testmo.net --project-id 4 --name "Run ${{ github.run_id }}" --source "unittests" --results "../build/junit-*.xml"


  stop-vm:
    name: Stop VM
    needs:
      - start-vm
      - check
    runs-on: trampoline
    if: ${{ always() }}
    steps:
      - name: Stop YC runner
        uses: yc-actions/yc-github-runner@v1
        with:
          mode: stop
          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
          github-token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          label: ${{ needs.start-vm.outputs.label }}
          instance-id: ${{ needs.start-vm.outputs.instance-id }}

  send-notifications:
    name: Send notifications
    needs:
      - stop-vm
    runs-on: trampoline
    if: ${{ failure() }}
    steps:
      - name: Send telegram message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          disable_web_page_preview: true
          format: markdown
          message: |
            Workflow *${{github.workflow}}* failed: ${{github.server_url}}/${{github.repository}}/actions/runs/${{github.run_id}}.
            Git ${{github.ref_type}}: *${{github.ref_name}}*.
            Commit:
            ```
            ${{github.event.head_commit.message}}
            ```

